//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolManagementEntities : DbContext
    {
        public SchoolManagementEntities()
            : base("name=SchoolManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Classroom> Classroom { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Lecturer> Lecturer { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<ResourcesManagement> ResourcesManagement { get; set; }
        public virtual DbSet<RoomManagement> RoomManagement { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<TimeManagement> TimeManagement { get; set; }
        public virtual DbSet<UserApp> UserApp { get; set; }
        public virtual DbSet<UserManager> UserManager { get; set; }
    }
}
